# -*- coding: utf-8 -*-

# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!
#
# Implementation of user interface


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(601, 402)
        self.central_widget = QtWidgets.QWidget(MainWindow)
        self.central_widget.setObjectName("central_widget")
        self.start_button = QtWidgets.QPushButton(self.central_widget)
        self.start_button.setGeometry(QtCore.QRect(9, 330, 581, 40))
        self.start_button.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(17)
        self.start_button.setFont(font)
        self.start_button.setObjectName("start_button")
        self.detail_view = QtWidgets.QTableWidget(self.central_widget)
        self.detail_view.setGeometry(QtCore.QRect(9, 9, 481, 311))
        self.detail_view.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.detail_view.setWordWrap(True)
        self.detail_view.setColumnCount(3)
        self.detail_view.setObjectName("detail_view")
        self.detail_view.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.detail_view.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.detail_view.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.detail_view.setHorizontalHeaderItem(2, item)
        self.detail_view.horizontalHeader().setStretchLastSection(True)
        self.layoutWidget = QtWidgets.QWidget(self.central_widget)
        self.layoutWidget.setGeometry(QtCore.QRect(500, 100, 91, 128))
        self.layoutWidget.setObjectName("layoutWidget")
        self.param_layout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.param_layout.setContentsMargins(0, 0, 0, 0)
        self.param_layout.setObjectName("param_layout")
        self.top_k_label = QtWidgets.QLabel(self.layoutWidget)
        self.top_k_label.setObjectName("top_k_label")
        self.param_layout.addWidget(self.top_k_label)
        self.top_k_text = QtWidgets.QLineEdit(self.layoutWidget)
        self.top_k_text.setObjectName("top_k_text")
        self.param_layout.addWidget(self.top_k_text)
        self.scroll_time_label = QtWidgets.QLabel(self.layoutWidget)
        self.scroll_time_label.setObjectName("scroll_time_label")
        self.param_layout.addWidget(self.scroll_time_label)
        self.scroll_time_text = QtWidgets.QLineEdit(self.layoutWidget)
        self.scroll_time_text.setObjectName("scroll_time_text")
        self.param_layout.addWidget(self.scroll_time_text)
        self.freq_label = QtWidgets.QLabel(self.layoutWidget)
        self.freq_label.setObjectName("freq_label")
        self.param_layout.addWidget(self.freq_label)
        self.freq_text = QtWidgets.QLineEdit(self.layoutWidget)
        self.freq_text.setObjectName("freq_text")
        self.param_layout.addWidget(self.freq_text)
        self.progress_label = QtWidgets.QLabel(self.central_widget)
        self.progress_label.setGeometry(QtCore.QRect(10, 380, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.progress_label.setFont(font)
        self.progress_label.setObjectName("progress_label")
        self.refresh_label = QtWidgets.QLabel(self.central_widget)
        self.refresh_label.setGeometry(QtCore.QRect(450, 380, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.refresh_label.setFont(font)
        self.refresh_label.setObjectName("refresh_label")
        self.seconds_label = QtWidgets.QLabel(self.central_widget)
        self.seconds_label.setGeometry(QtCore.QRect(550, 380, 47, 21))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(10)
        font.setItalic(True)
        self.seconds_label.setFont(font)
        self.seconds_label.setObjectName("seconds_label")
        self.stop_button = QtWidgets.QPushButton(self.central_widget)
        self.stop_button.setEnabled(False)
        self.stop_button.hide()
        self.stop_button.setGeometry(QtCore.QRect(10, 330, 581, 40))
        self.stop_button.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(17)
        self.stop_button.setFont(font)
        self.stop_button.setObjectName("stop_button")
        MainWindow.setCentralWidget(self.central_widget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "GroupWorm"))
        self.start_button.setText(_translate("MainWindow", "Start"))
        item = self.detail_view.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Time"))
        item = self.detail_view.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Feed ID"))
        item = self.detail_view.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Link"))
        self.top_k_label.setText(_translate("MainWindow", "Top-K"))
        self.top_k_text.setText(_translate("MainWindow", "10"))
        self.scroll_time_label.setText(_translate("MainWindow", "Scroll"))
        self.scroll_time_text.setText(_translate("MainWindow", "5"))
        self.freq_label.setText(_translate("MainWindow", "Frequency (in s)"))
        self.freq_text.setText(_translate("MainWindow", "60"))
        self.progress_label.setText(_translate("MainWindow", "Ready"))
        self.refresh_label.setText(_translate("MainWindow", "Refresh in (s): "))
        self.seconds_label.setText(_translate("MainWindow", "0"))
        self.stop_button.setText(_translate("MainWindow", "Stop"))
        
class Ui_SettingDialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("SettingDialog")
        Dialog.resize(400, 231)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.group_id_label = QtWidgets.QLabel(Dialog)
        self.group_id_label.setObjectName("group_id_label")
        self.verticalLayout.addWidget(self.group_id_label)
        self.group_id_text = QtWidgets.QTextEdit(Dialog)
        self.group_id_text.setObjectName("group_id_text")
        self.verticalLayout.addWidget(self.group_id_text)
        self.keywords_label = QtWidgets.QLabel(Dialog)
        self.keywords_label.setObjectName("keywords_label")
        self.verticalLayout.addWidget(self.keywords_label)
        self.keywords_text = QtWidgets.QTextEdit(Dialog)
        self.keywords_text.setObjectName("keywords_text")
        self.verticalLayout.addWidget(self.keywords_text)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.group_id_label.setText(_translate("Dialog", "Group ID"))
        self.keywords_label.setText(_translate("Dialog", "Keyword(s)"))
              
class Ui_LoginDialog(object):
    def setupUi(self, LoginDialog):
        LoginDialog.setObjectName("LoginDialog")
        LoginDialog.resize(582, 121)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(LoginDialog.sizePolicy().hasHeightForWidth())
        LoginDialog.setSizePolicy(sizePolicy)
        self.buttonBox = QtWidgets.QDialogButtonBox(LoginDialog)
        self.buttonBox.setGeometry(QtCore.QRect(420, 50, 151, 61))
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.buttonBox.accepted.connect(LoginDialog.accept)
        self.buttonBox.rejected.connect(LoginDialog.reject)
        self.facebook_label = QtWidgets.QLabel(LoginDialog)
        self.facebook_label.setGeometry(QtCore.QRect(10, 10, 561, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(15)
        self.facebook_label.setFont(font)
        self.facebook_label.setObjectName("facebook_label")
        self.widget = QtWidgets.QWidget(LoginDialog)
        self.widget.setGeometry(QtCore.QRect(10, 50, 401, 31))
        self.widget.setObjectName("widget")
        self.username_layout = QtWidgets.QHBoxLayout(self.widget)
        self.username_layout.setContentsMargins(0, 0, 0, 0)
        self.username_layout.setSpacing(6)
        self.username_layout.setObjectName("username_layout")
        self.username_label = QtWidgets.QLabel(self.widget)
        self.username_label.setObjectName("username_label")
        self.username_layout.addWidget(self.username_label)
        self.username_text = QtWidgets.QLineEdit(self.widget)
        self.username_text.setObjectName("username_text")
        self.username_layout.addWidget(self.username_text)
        self.widget1 = QtWidgets.QWidget(LoginDialog)
        self.widget1.setGeometry(QtCore.QRect(10, 80, 401, 31))
        self.widget1.setObjectName("widget1")
        self.passwd_layout = QtWidgets.QHBoxLayout(self.widget1)
        self.passwd_layout.setContentsMargins(0, 0, 0, 0)
        self.passwd_layout.setSpacing(6)
        self.passwd_layout.setObjectName("passwd_layout")
        self.passwd_label = QtWidgets.QLabel(self.widget1)
        self.passwd_label.setObjectName("passwd_label")
        self.passwd_layout.addWidget(self.passwd_label)
        self.password_text = QtWidgets.QLineEdit(self.widget1)
        self.password_text.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_text.setObjectName("password_text")
        self.passwd_layout.addWidget(self.password_text)

        self.retranslateUi(LoginDialog)
        QtCore.QMetaObject.connectSlotsByName(LoginDialog)

    def retranslateUi(self, LoginDialog):
        _translate = QtCore.QCoreApplication.translate
        LoginDialog.setWindowTitle(_translate("LoginDialog", "Facebook Login"))
        self.facebook_label.setText(_translate("LoginDialog", "Facebook Login"))
        self.username_label.setText(_translate("LoginDialog", "Username"))
        self.passwd_label.setText(_translate("LoginDialog", "Password"))